[package]
name = "cborjson"
version = "0.1.0"
authors = ["Grant Perry <grant.perry@csiro.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_cbor = "0.10"
